POST http://localhost:8080/car/adm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4YThhODZlYTgxOWFiNjZhMDE4MTlhYjZlOWM1MDAwMCIsImlhdCI6MTY1NjI0ODcwOCwiZXhwIjoxNjU2Mjg0NzA4LCJpc3MiOiJqd3QgcHJvZHVjdGlvbiIsInJvbGUiOiJBRE1JTiJ9.0ZYYOmDJbvAjufOyZNmC0GuTDm3HW-t1r6oB7NzJG98


{
  "name": "mers",
  "number": "40B777KA"
}

###

GET http://localhost:8080/car/adm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4YThhODZlYTgxOWFiNjZhMDE4MTlhYjZlOWM1MDAwMCIsImlhdCI6MTY1NjI0ODcwOCwiZXhwIjoxNjU2Mjg0NzA4LCJpc3MiOiJqd3QgcHJvZHVjdGlvbiIsInJvbGUiOiJBRE1JTiJ9.0ZYYOmDJbvAjufOyZNmC0GuTDm3HW-t1r6oB7NzJG98
###

PUT http://localhost:8080/car/adm/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4YThhODZlYTgxOWFiNjZhMDE4MTlhYjZlOWM1MDAwMCIsImlhdCI6MTY1NjI0ODcwOCwiZXhwIjoxNjU2Mjg0NzA4LCJpc3MiOiJqd3QgcHJvZHVjdGlvbiIsInJvbGUiOiJBRE1JTiJ9.0ZYYOmDJbvAjufOyZNmC0GuTDm3HW-t1r6oB7NzJG98

{
  "name": "labo",
  "number": "40K777LA"
}

###

DELETE http://localhost:8080/car/adm/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4YThhODZlYTgxOWFiNjZhMDE4MTlhYjZlOWM1MDAwMCIsImlhdCI6MTY1NjI0ODcwOCwiZXhwIjoxNjU2Mjg0NzA4LCJpc3MiOiJqd3QgcHJvZHVjdGlvbiIsInJvbGUiOiJBRE1JTiJ9.0ZYYOmDJbvAjufOyZNmC0GuTDm3HW-t1r6oB7NzJG98
