POST http://localhost:8080/distr/adm
Content-Type: application/json

{
  "name": "Vali",
  "surname": "Vali",
  "userName": "@valijon",
  "distrCode": "VALI01",
  "phoneNumber": "+9989145268964"
}

###

GET http://localhost:8080/distr/adm?page=0&size=4
Content-Type: application/json

###

PUT http://localhost:8080/distr/adm/7
Content-Type: application/json

{
  "name": "Ali",
  "surname": "Aliyev",
  "userName": "@valijon",
  "distrCode": "VALI01",
  "phoneNumber": "+9989145268456"
}

###
DELETE http://localhost:8080/distr/adm/5