POST http://localhost:8080/profile/adm
Content-Type: application/json
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjU1OTkxNDg2LCJleHAiOjE2NTYwMjc0ODYsImlzcyI6Imp3dCBwcm9kdWN0aW9uIiwicm9sZSI6IkFETUlOIn0.U7LHWvQg5dh5_5ums0U8gs9wmRiLcWWDtzSeJyLcpRY

{
  "name": "alihon",
  "surname": "alihonov",
  "userName": "@alihon",
  "phone": "+998915874963",
  "password": "alihon568"
}